name = "quantum_tree"
version = "0.1.0"
defaultTargets = ["QuantumTree"]

[leanOptions]
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.31.0"

[[lean_lib]]
name = "QuantumTree"
